server:
  port: 8087

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

Token:
  url: ${GIGACHAT_URL}
  key: ${GIGACHAT_KEY}