server:
  port: 8084

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

OpenWeatherMap:
  key: ${OPENWEATHERMAP_KEY}
  urlGetWeather: http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API key}&units=metric&lang=ru