server:
  port: 8084

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

OpenWeatherMap:
  key: ${OPENWEATHERMAP_KEY}
  urlGetWeather: ${OPENWEATHERMAP_URL}