server:
  port: 8085

bot:
  name: ${BOT_NAME_ADMIN}
  token: ${BOT_TOKEN_ADMIN}

spring:
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}

  jpa:
    generate-ddl: true
    open-in-view: false